### PR TITLE
fix a bug, made some test and refactor a bit

### PR DESCRIPTION
**Pull request by davidt99**
I think this time I got it.
Made an integrity test - I generated random file based on a seed and ssdeeped them with the official implementation. The test generating the files and ssdeep them and then comparing results.
I refactored a bit, so the bytes and the file methods now use the same core code.

### CODE REVIEW

**Comment by glaslos** [comment]
Can you remove this line: https://github.com/glaslos/ssdeep/blob/master/.travis.yml#L4 or fix the backwards compatibility issue?

**Comment by glaslos** [comment]
Could you also add a `make benchcmp` as a comment?

**Comment by davidt99** [comment]
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkDistance-8        9101          9419          +3.49%
BenchmarkRollingHash-8     3.03          3.19          +5.28%
BenchmarkSumHash-8         33.4          34.2          +2.40%
BenchmarkBlockSize-8       11.1          6.70          -39.64%
BenchmarkProcessByte-8     29.7          28.6          -3.70%
```
Not sure why there is a performance improvement for GetBlockSize - It didn't change.

**Comment by glaslos** [comment]
Yeah, no clue why there is that performance improvement. I was running a benchcmp as well and could reproduce your observation. Thanks for fixing this issue! I will create a new release later today.

**Pull request merged**
